version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
  reviewers:
    - richardbporter
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
  reviewers:
    - richardbporter
- package-ecosystem: devcontainers
   directory: "/"
   schedule:
     interval: monthly
