sudo: false

language: php

php:
- '7.3'

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true

before_install:
  - composer self-update
  - cd .. && mkdir Commands
  - mv drush-users-commands/ Commands/UsersCommands
  - cd Commands/UsersCommands

install:
  - COMPOSER_MEMORY_LIMIT=-1 composer install --no-suggest --prefer-source --no-scripts
  - ./vendor/bin/phpcs --config-set ignore_warnings_on_exit 1

script:
  - ./vendor/bin/phpcs --standard=PSR2 . --ignore='.scenarios.lock,vendor,tests/coverage'
  - ./vendor/bin/phpunit
