sudo: false

language: php

php:
  - '7.4'
  - '8.1'

matrix:
  fast_finish: true

services:
  - mysql

before_install:
  - composer self-update

install:
  - composer install --no-scripts
  - ./vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
  - ./vendor/bin/drush site:install testing --root sut --db-url mysql://root@localhost/drupal --yes

script:
  - ./vendor/bin/phpcs --standard=PSR2 --ignore='sut,vendor' .
  - ./vendor/bin/phpunit
