sudo: false

language: php

php:
  - '7.3'

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true

services:
  - mysql

before_install:
  - composer self-update

install:
  - composer install --no-scripts
  - ./vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
  - ./vendor/bin/drush site:install --root sut --db-url mysql://root@localhost/drupal

script:
  - ./vendor/bin/phpcs --standard=PSR2 . --ignore='.scenarios.lock,vendor,tests/coverage'
  - ./vendor/bin/phpunit
