sudo: false

language: php

php:
  - '7.4'

cache:
  directories:
    - $HOME/.drush/cache

matrix:
  fast_finish: true

services:
  - mysql

before_install:
  - composer self-update

install:
  - composer install --no-scripts
  - ./vendor/bin/phpcs --config-set ignore_warnings_on_exit 1

script:
  - ./vendor/bin/phpcs --standard=PSR2 --ignore='sut,vendor' .
  - ./vendor/bin/phpunit
