name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4, 8.1]
    steps:
    - uses: actions/checkout@v3
    - name: Start MySQL
      run: sudo /etc/init.d/mysql start
    - name: Validate composer.json and composer.lock
      run: composer validate --strict
    - name: Install dependencies
      run: composer install --prefer-dist --no-scripts --no-suggest --no-interaction
    - name: Ignore PHPCS warnings
      run: ./vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
    - name: Install drupal
      run: ./vendor/bin/drush site:install testing --root sut --db-url mysql://root:root@localhost/drupal --yes
    - name: Run code sniffer
      run: ./vendor/bin/phpcs --standard=PSR2 --ignore='sut,vendor' .
    - name: Run unit tests
      run: ./vendor/bin/phpunit
