name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: drupal
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4, 8.1]
    steps:
    - uses: actions/checkout@v3
    - name: Validate composer.json and composer.lock
      run: composer validate --strict
    - name: Install dependencies
      run: composer install --prefer-dist --no-scripts --no-suggest --no-interaction
    - name: Install drupal
      run: ./vendor/bin/drush site:install testing --root sut --db-url mysql://root@localhost/drupal --yes
    - name: Run code sniffer
      run: ./vendor/bin/phpcs --standard=PSR2 --ignore='sut,vendor' .
    - name: Run unit tests
      run: ./vendor/bin/phpunit
