name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: drupal
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4, 8.1]
    steps:
    - uses: actions/checkout@v3
    - name: Validate composer.json and composer.lock
      run: composer validate --strict
    - name: Install dependencies
      run: composer install --prefer-dist --no-scripts --no-suggest --no-interaction
